apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
  labels:
    app: my-kafka-cluster
spec:
  kafka:
    replicas: 1
    listeners:
      plain: {}
    storage:
      type: ephemeral
   #  type: persistent-claim
   #  size: 10Gi
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
   #  type: persistent-claim
   #  size: 10Gi

